### PR TITLE
Fixed @:enum warnings for haxe 4+

### PR DESCRIPTION
**Pull request by deepnight**
Simply changed the #if version to Haxe4+ instead of just Haxe5+

### CODE REVIEW

**Comment by kLabz** [comment]
That won't work with haxe < 4.3.2 though :/

**Comment by deepnight** [comment]
My bad! I will rework the PR to fix that

**Comment by deepnight** [comment]
Oh, I just noticed that haxe_ver checks don't support actual number versions, just string comparisons 🤔

**Comment by kLabz** [comment]
There's a way to compare semver versions too but I keep forgetting the syntax :sweat_smile:

**Pull request closed without merging**
