### PR TITLE
Added extension field to column for filepicker types

### PR DESCRIPTION
**Pull request by jefvel**

### CODE REVIEW

**Comment by ncannasse** [comment]
I think we need to find a way to store these IDE/Display-only-properties so that we don't have to add them to CDB library each time HIDE requires a new one.

**Comment by jefvel** [comment]
Ah yeah. I guess itcould go into `props.json` in HIDE instead?

**Comment by ncannasse** [comment]
No, its part of data validation but I think we need some extra
configuration. Will try to refactor something soon

**Comment by ncannasse** [comment]
There's now some "editor" property as part of the column data which is here to store things that are only required for authoring the data, and not required for manipulating it / type system / etc.
You could repost your Hide patch using this data instead.

**Pull request closed without merging**
