### PR TITLE
Added Curve Datatype

### PR DESCRIPTION
**Pull request by onehundredfeet**
Ported the HIDE 1D Curve Datatype to CastleDB.
Allows for the storing of Curves inside the CastleDB format instead of limited to just prefabs.
Added no significant UI functionality to CastleDB UI.

### CODE REVIEW

**Comment by ncannasse** [comment]
TBH I think that's a bit outside of CDB scope. Curves are a quite specific type of data and there might be several way of implementing them with different precision etc. So I prefer to keep them at the prefab level where there can be eventually several concurrent solutions for the same kind of problem.

**Comment by onehundredfeet** [comment]
I understand the perspective.  We use curves extensively to tune combat values. For tuning large numbers of variants, the DB nature of castle is far preferable to the loose object style of prefabs.

I would be happy to field additional feature requests and extend the curve functionality to capture the cases you mention. I feel that 1D curves are common enough that they would be very valuable.

I do understand the lens you are using, but just ask for you to take a moment to consider it again.

**Comment by ncannasse** [comment]
What you can do is actually have your CDB data and reference a CDB id from the curve prefab so the prefab data is linked to the CBD id. Is that not good enough ?

**Comment by onehundredfeet** [comment]
Thanks for considering it.

**Comment by onehundredfeet** [comment]
I see someone added curves :)

**Pull request closed without merging**
